// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "f79d5f19c5dbee460f00184787f53bb788d0a390c59ce2613c3886b162c08768")
